(source "kutkevich" "http://elpa.kutkevich.org/mirror/")

;; (source "ELPA" "http://tromey.com/elpa/")
;; (source "melpa-stable" "http://stable.melpa.org/packages/")
;; (source SC)
;; (source gnu)
;; (source marmalade)
;; (source melpa)
;; (source org)

;; (depends-on "auto-complete-emacs-lisp" "Auto-complete sources for emacs lisp") ;<http://www.cx4a.org/pub/auto-complete-emacs-lisp.el>
;; (depends-on "ebuild-mode" "Gentoo ebuild and eclass mode <http://wiki.gentoo.org/wiki/Project:Emacs>") ;http://dev.gentoo.org/~ulm/emacs/ebuild-mode-1.26.tar.xz
;; (depends-on "erise")
;; (depends-on "mmm-mode")
;; (depends-on "org-readme")

;; (depends-on "ac-html-bootstrap")
(depends-on "ac-etags")

(depends-on "ac-html" "0.31")
(depends-on "web-completion-data") ;used by ad-html

(depends-on "auto-complete")
(depends-on "auto-complete-chunk")
(depends-on "auto-complete-nxml")
(depends-on "auto-complete-pcmp")

(depends-on "ag")
(depends-on "anzu")
(depends-on "apache-mode")
(depends-on "bash-completion")
(depends-on "browse-kill-ring")
(depends-on "cask")
(depends-on "cider" "0.9.1")
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "column-marker")
(depends-on "crontab-mode")
(depends-on "csv-mode")
(depends-on "dash")
(depends-on "deft")
(depends-on "diffview")
(depends-on "direx")
(depends-on "discover-my-major")
(depends-on "dockerfile-mode")
(depends-on "elpa-mirror")
(depends-on "etags-select")
(depends-on "ethan-wspace")
(depends-on "expand-region")
(depends-on "ferm-mode" :git "https://github.com/danil/ferm-mode.git" :files ("ferm-mode.el") "Major mode for ferm iptables tool <https://gitorious.org/kaction-emacs/ferm-mode>, <http://ferm.foo-projects.org>")
(depends-on "findr")
(depends-on "fish-mode")
(depends-on "flycheck")
(depends-on "git-gutter")
(depends-on "git-timemachine")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "go-mode")
(depends-on "haml-mode")
(depends-on "highlight-symbol")
(depends-on "ido-describe-bindings")
(depends-on "ido-occur")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "ido-yes-or-no")
(depends-on "jade-mode")
(depends-on "js2-mode" "20150909")
(depends-on "jsfmt")
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "kill-ring-ido")
(depends-on "less-css-mode")
(depends-on "list-unicode-display")
(depends-on "lua-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "nginx-mode")
(depends-on "nodejs-repl")
(depends-on "nvm" :git "https://github.com/danil/nvm.el" :files ("nvm.el") "Manage Node versions within Emacs")
(depends-on "org" "20151005")
(depends-on "org-ac")
(depends-on "package-build")
(depends-on "php-mode")
(depends-on "point-stack")
(depends-on "pretty-lambdada")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "quelpa")
(depends-on "quickrun")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "rbenv")
(depends-on "rspec-mode")
(depends-on "ruby-guard")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-pry" :git "https://github.com/jacott/emacs-pry.git" :files ("*" (:exclude ".git" ".gitignore" "COPYING" "README.md" "TODO")) "Pry support within Emacs")
(depends-on "ruby-refactor")
(depends-on "ruby-tools")
(depends-on "rust-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "simp")
(depends-on "slim-mode")

(depends-on "smart-mode-line")
(depends-on "rich-minority")

(depends-on "smartparens")
(depends-on "smex")
(depends-on "speed-type")
(depends-on "systemd")
(depends-on "toml-mode")
(depends-on "transpose-frame")
(depends-on "twittering-mode")
(depends-on "undo-tree")
(depends-on "web-mode")
(depends-on "window-numbering")
(depends-on "yaml-mode")
(depends-on "yascroll")
(depends-on "yasnippet")
(depends-on "ztree")
(depends-on "yasnippet")
(depends-on "yasnippets" :git "https://github.com/rejeep/yasnippets.git" :files ("*" (:exclude ".git" ".gitignore" "README.markdown")) "Comprehensive collection of yasnippets")
