(source "kutkevich" "http://elpa.kutkevich.org/mirror/")

(source "ELPA" "http://tromey.com/elpa/")
(source "melpa-stable" "http://stable.melpa.org/packages/")
(source gnu)
(source melpa)
(source org)

;; (depends-on "erise")
;; (depends-on "lfe-mode")
;; (depends-on "mmm-mode")
;; (depends-on "org-readme")
;; (depends-on "yafolding")

(depends-on "ac-html" "0.31") ;i can not setup new version
(depends-on "web-completion-data") ;used by ad-html

(depends-on "cider" "0.10.0") ;i do not want upgrade "cider-nrepl plugin"
(depends-on "clojure-mode")

(depends-on "magit")
(depends-on "magit-popup")

(depends-on "org" "20150929") ;fixme: respects version!!!!!!!!!!!!!!!!!!!!!!
(depends-on "org-ac")

;; (depends-on "ac-html-bootstrap")
;; (depends-on "auto-complete-emacs-lisp" :url "http://www.cx4a.org/pub/auto-complete-emacs-lisp.el" "Auto-complete sources for emacs lisp")
(depends-on "ac-etags")
(depends-on "ac-ispell")
(depends-on "auto-complete")
(depends-on "auto-complete-chunk")
(depends-on "auto-complete-nxml")
(depends-on "auto-complete-pcmp")

(depends-on "ag")
(depends-on "anzu") ;isearch and query-replace extension
(depends-on "apache-mode")
(depends-on "bash-completion")
(depends-on "cask")
(depends-on "column-marker")
(depends-on "corral") ;smartparens replacement (quotes/parentheses/delimiters manager)
(depends-on "crontab-mode")
(depends-on "csv-mode")
(depends-on "cycle-quotes")
(depends-on "dash")
(depends-on "deft")
(depends-on "diffview")
(depends-on "dim")
(depends-on "direx")
(depends-on "dockerfile-mode")
(depends-on "dumb-jump")
(depends-on "ebuild-mode" :git "https://github.com/emacsmirror/ebuild-mode.git" "Gentoo ebuild and eclass mode <http://wiki.gentoo.org/wiki/Project:Emacs>, <https://packages.gentoo.org/packages/app-emacs/ebuild-mode>") ;http://dev.gentoo.org/~ulm/emacs/ebuild-mode-1.26.tar.xz
(depends-on "elpa-mirror")
(depends-on "etags-select")
(depends-on "ethan-wspace")
(depends-on "expand-region")
(depends-on "ferm-mode" :git "https://github.com/danil/ferm-mode.git" :files ("ferm-mode.el") "Major mode for ferm iptables tool <https://gitorious.org/kaction-emacs/ferm-mode>, <http://ferm.foo-projects.org>")
(depends-on "find-temp-file")
(depends-on "findr")
(depends-on "fish-mode")
(depends-on "flycheck")
(depends-on "flycheck-bashate")
(depends-on "git-gutter")
(depends-on "git-timemachine")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

(depends-on "go-autocomplete")
(depends-on "go-mode")
(depends-on "go-projectile")
(depends-on "go-snippets")
(depends-on "gotest")

(depends-on "google-translate")
(depends-on "haml-mode")
(depends-on "highlight-symbol")

(depends-on "crm-custom")
(depends-on "css-comb") ;css formater
(depends-on "ibuffer-vc")
(depends-on "ido-clever-match")
(depends-on "ido-describe-bindings")
(depends-on "ido-occur")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "ido-yes-or-no")
(depends-on "smex")

;;; JavaScript.
(depends-on "coffee-mode")
(depends-on "jade-mode")
(depends-on "js2-mode")
(depends-on "jsfmt")
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "literate-coffee-mode")

(depends-on "browse-kill-ring")
(depends-on "kill-ring-ido")
(depends-on "noflet")

(depends-on "less-css-mode")
(depends-on "list-unicode-display")
(depends-on "lua-mode")
(depends-on "markdown-mode")
(depends-on "markdownfmt")
(depends-on "mediawiki")
(depends-on "modalka")
(depends-on "multiple-cursors")
(depends-on "mustache-mode")
(depends-on "narrow-indirect")
(depends-on "nginx-mode")
(depends-on "nodejs-repl")
(depends-on "origami")
(depends-on "package-build")
(depends-on "php-mode")
(depends-on "point-stack")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "pt") ;the platinum searcher (ag and ack replacement <https://github.com/monochromegane/the_platinum_searcher>)
(depends-on "quelpa")
(depends-on "quickrun")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "restclient")

(depends-on "minitest")
(depends-on "multi-compile")
(depends-on "rbenv")
(depends-on "rspec-mode")
(depends-on "ruby-guard")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-pry" :git "https://github.com/jacott/emacs-pry.git" :files ("*" (:exclude ".git" ".gitignore" "COPYING" "README.md" "TODO")) "Pry support within Emacs")
(depends-on "ruby-refactor")
(depends-on "ruby-tools")

;; (depends-on "racer")
;; (depends-on "flycheck-rust") ;buggy(
(depends-on "rust-mode")

(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "simp")
(depends-on "slim-mode")

(depends-on "smart-mode-line")
(depends-on "rich-minority")

(depends-on "sed-mode")
(depends-on "speed-type")
(depends-on "systemd")
(depends-on "toml-mode")
(depends-on "transpose-frame")
(depends-on "twittering-mode")
(depends-on "undo-tree")
(depends-on "unicode-troll-stopper")
(depends-on "vlf")
(depends-on "web-mode")
(depends-on "window-numbering")
(depends-on "yaml-mode")
;; (depends-on "yascroll")
(depends-on "yasnippet")
(depends-on "yasnippet")
(depends-on "yasnippet-snippets" :git "https://github.com/AndreaCrotti/yasnippet-snippets.git" :files ("*" (:exclude ".git" ".gitignore" ".nosearch" "CONTRIBUTORS.txt" "LICENSE" "README.md" "rename_add_contr.py")))
(depends-on "yasnippets" :git "https://github.com/rejeep/yasnippets.git" :files ("*" (:exclude ".git" ".gitignore" "README.markdown")) "Comprehensive collection of yasnippets")
(depends-on "ztree")
